apiVersion: v1
kind: Service
metadata:
  name: drupal
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30085
      protocol: TCP
      name: http
